export const ACTION_TYPES = Object.freeze({
  COUNTRIES_FETCH_START: "COUNTRIES_FETCH_START",
  COUNTRIES_FETCH_SUCCESS: "COUNTRIES_FETCH_SUCCESS",
  COUNTRIES_FETCH_ERROR: "COUNTRIES_FETCH_ERROR"
});
